### ISSUE TITLE
MemoryFileSystem File.readAsBytesSync() failure

### ISSUE THREAD

**Issue by simmule-turner** [google/file.dart#122]
MemoryFileSystem File.readAsBytesSync() produces different results than the default File.readAsBytesSync(). Adding Uint8List.fromList to the resultant bytes corrects the problem.

**Comment by simmule-turner** [comment]
When reading from a local file the data is correct in bytes. Once written to a MemoryFileSystem the data is retrieved incorrectly and requires an extra level of translation before it works. The below code does not work:
        List<int> bytes = File(_path + '/' + filename).readAsBytesSync();
        mfs.file('a_${i}').writeAsBytesSync(bytes);
        List<int> xbytes = mfs.file('a_${i}').readAsBytesSync();

The above code does not produce a displayable image from bytes from the original file. However, adding this line allows an image to be displayed properly without other changes (In the example here I use a MemoryImage.
          xbytes = Uint8List.fromList(xbytes);

The impact is that a MemoryFileSystem.file can not be used for a FileImage provider.

**Comment by simmule-turner** [comment]
LocalFileSystem() has the correct behavior.

**Comment by jamesderlin** [comment]
I think that this should have been fixed by https://github.com/google/file.dart/pull/123.

**Comment by dnfield** [comment]
Closing on assumption #123 fixed this
