### ISSUE TITLE
record_replay depricated

### ISSUE THREAD

**Issue by Gorniv** [google/file.dart#167]
how change RecordingFileSystem in the new version?

**Comment by jamesderlin** [comment]
I don't understand your question.  Could you try rephrasing it?  Is there a specific problem you're encountering?

**Comment by radvansky-tomas** [comment]
If you use null safety repo RecordingFileSystem is not available

**Comment by tzutolin** [comment]
Same problem here:

`~/flutter/.pub-cache/hosted/pub.dartlang.org/tool_base-1.9.5+3/lib/src/base/file_system.dart:8:8: Error: Error when reading '~/flutter/.pub-cache/hosted/pub.dartlang.org/file-6.0.0-nullsafety.1/lib/record_replay.dart': No such file or directory
import 'package:file/record_replay.dart';
       ^
~/flutter/.pub-cache/hosted/pub.dartlang.org/tool_base-1.9.5+3/lib/src/base/process_manager.dart:8:8: Error: Error when reading '~/flutter/.pub-cache/hosted/pub.dartlang.org/process-4.0.0-nullsafety.1/lib/record_replay.dart': No such file or directory
import 'package:process/record_replay.dart';
       ^
~/flutter/.pub-cache/hosted/pub.dartlang.org/tool_base-1.9.5+3/lib/src/base/file_system.dart:34:1: Error: Type 'RecordingFileSystem' not found.
RecordingFileSystem getRecordingFileSystem(String location) {
^^^^^^^^^^^^^^^^^^^
~/flutter/.pub-cache/hosted/pub.dartlang.org/tool_base-1.9.5+3/lib/src/base/file_system.dart:50:1: Error: Type 'ReplayFileSystem' not found.
ReplayFileSystem getReplayFileSystem(String location) {
^^^^^^^^^^^^^^^^
~/flutter/.pub-cache/hosted/pub.dartlang.org/tool_base-1.9.5+3/lib/src/base/process_manager.dart:28:1: Error: Type 'RecordingProcessManager' not found.
RecordingProcessManager getRecordingProcessManager(String location) {
^^^^^^^^^^^^^^^^^^^^^^^
~/flutter/.pub-cache/hosted/pub.dartlang.org/tool_base-1.9.5+3/lib/src/base/process_manager.dart:44:8: Error: Type 'ReplayProcessManager' not found.
Future<ReplayProcessManager> getReplayProcessManager(String location) async {
       ^^^^^^^^^^^^^^^^^^^^
~/flutter/.pub-cache/hosted/pub.dartlang.org/tool_base-1.9.5+3/lib/src/base/file_system.dart:36:9: Error: 'RecordingFileSystem' isn't a type.
  final RecordingFileSystem fileSystem = RecordingFileSystem(
        ^^^^^^^^^^^^^^^^^^^
~/flutter/.pub-cache/hosted/pub.dartlang.org/tool_base-1.9.5+3/lib/src/base/file_system.dart:36:42: Error: Method not found: 'RecordingFileSystem'.
  final RecordingFileSystem fileSystem = RecordingFileSystem(
                                         ^^^^^^^^^^^^^^^^^^^
~/flutter/.pub-cache/hosted/pub.dartlang.org/tool_base-1.9.5+3/lib/src/base/file_system.dart:52:10: Error: Method not found: 'ReplayFileSystem'.
  return ReplayFileSystem(recording: dir);
         ^^^^^^^^^^^^^^^^
~/flutter/.pub-cache/hosted/pub.dartlang.org/tool_base-1.9.5+3/lib/src/base/process_manager.dart:31:9: Error: 'RecordingProcessManager' isn't a type.
  final RecordingProcessManager manager = RecordingProcessManager(delegate, dir);`

**Comment by mjakareya** [comment]
Also faceing the same problem:

/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/tool_base-1.9.5+3/lib/src/base/file_system.dart:8:8: Error: Error when reading '/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/file-6.0.0-nullsafety.2/lib/record_replay.dart':
 The system cannot find the file specified.

import 'package:file/record_replay.dart';
       ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/tool_base-1.9.5+3/lib/src/base/process_manager.dart:8:8: Error: Error when reading '/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/process-4.0.0-nullsafety.2/lib/record_replay
.dart': The system cannot find the file specified.

import 'package:process/record_replay.dart';
       ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/tool_base-1.9.5+3/lib/src/base/file_system.dart:34:1: Error: Type 'RecordingFileSystem' not found.
RecordingFileSystem getRecordingFileSystem(String location) {
^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/tool_base-1.9.5+3/lib/src/base/file_system.dart:50:1: Error: Type 'ReplayFileSystem' not found.
ReplayFileSystem getReplayFileSystem(String location) {
^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/tool_base-1.9.5+3/lib/src/base/process_manager.dart:28:1: Error: Type 'RecordingProcessManager' not found.
RecordingProcessManager getRecordingProcessManager(String location) {
^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/tool_base-1.9.5+3/lib/src/base/process_manager.dart:44:8: Error: Type 'ReplayProcessManager' not found.
Future<ReplayProcessManager> getReplayProcessManager(String location) async {
       ^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/tool_base-1.9.5+3/lib/src/base/file_system.dart:36:9: Error: 'RecordingFileSystem' isn't a type.
  final RecordingFileSystem fileSystem = RecordingFileSystem(
        ^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/tool_base-1.9.5+3/lib/src/base/file_system.dart:36:42: Error: Method not found: 'RecordingFileSystem'.
  final RecordingFileSystem fileSystem = RecordingFileSystem(
                                         ^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/tool_base-1.9.5+3/lib/src/base/file_system.dart:52:10: Error: Method not found: 'ReplayFileSystem'.
  return ReplayFileSystem(recording: dir);
         ^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/tool_base-1.9.5+3/lib/src/base/process_manager.dart:31:9: Error: 'RecordingProcessManager' isn't a type.
  final RecordingProcessManager manager = RecordingProcessManager(delegate, dir);

**Comment by jamesderlin** [comment]
record_replay was intentionally removed (I'm guessing because it's incompatible with the transition to null safety).

Again, it's not clear what this issue is about.  If you're requesting that it not be reinstated, I don't think that's feasible.

**Comment by tvolkert** [comment]
As @jamesderlin says, record_replay was removed -- partly because the migration to sound null safety was proving very difficult, but moreover because the library was very buggy and had n^2 implementations in many places.
