### ISSUE TITLE
Support async for all methods 

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [google/file.dart#171]
I'm playing around with creating a dart version of SSHFS but since all these calls are async, I can't use it to return sync data when the class calls for it. For example, to grab a file, it's sync and there's isn't an async version of this method. Can we have methods for that built in as well? I'll add it to my class manually, but the names are taken by the sync methods. I prefer file() for Async and fileSync() for sync.
```
File file(path) {...}
```

**Comment by dnfield** [comment]
Doesn't file just run a constructor?

**Comment by ThinkDigitalSoftware** [comment]
I'm not sure, but in order to create a file, I'll need data. And this data is located over the network (sftp) so it's going to be an async call

**Comment by dnfield** [comment]
One you have the file object you use either create or createSync.  Or check if it exists/existsSync

**Comment by ThinkDigitalSoftware** [comment]
I don't understand. How do I get the file from the network synchronously? This is a, "fetch me this file from the filesystem" call, right?

**Comment by dnfield** [comment]
You'd have to use readAsBytes(Sync) or as string etc.

**Comment by ThinkDigitalSoftware** [comment]
> You'd have to use readAsBytes(Sync) or as string etc.

It's over the network. There are no sync methods available.
Here's a link to [sshfs](https://github.com/libfuse/sshfs) for context

**Comment by dnfield** [comment]
Sure, so you'd either throw unimplemented or if possible use blocking network calls if possible

**Comment by dnfield** [comment]
So it would look like this

```dart
final File file = fs.file('pathtofile');
final bytes = await file.readAsBytes();
```

**Comment by ThinkDigitalSoftware** [comment]
Doing this will convert the method to async and it'll break the contract of the interface. Also, I'll need to fetch the file from the server first before reading it in.

**Comment by dnfield** [comment]
Creating the file object does not actually fetch bytes

**Comment by ThinkDigitalSoftware** [comment]
But I still don't have a way to reference a remote file without using an async method. I'm basically stuck without async abilities. Is that not possible to add?

**Comment by dnfield** [comment]
The reference doesn't have to know if the file exists or anything until you start calling methods on it.

**Comment by ThinkDigitalSoftware** [comment]
Ok, I think I'm understanding what you're getting at.
