### ISSUE TITLE
Migrate mixins to be mixin declarations

### ISSUE THREAD

**Issue by jakemac53** [google/file.dart#209]
With the "class modifiers" feature coming, we need to migrate all of the `abstract class` declarations that are used as mixins to be either `mixin` declarations, or possibly `mixin class` declarations.

This will likely be a blocker for enabling Dart 3 internally.

**Comment by jakemac53** [comment]
cc @itsjustkevin I am not sure if there is a good meta issue to attach this to for tracking

**Comment by itsjustkevin** [comment]
@devoncarew do you have the correct permissions to tag this somehow?

**Comment by devoncarew** [comment]
For sure, I can apply labels here. But probably good to also add as an item in a meta-issue in the sdk repo?

**Comment by devoncarew** [comment]
Probably useful to have a proxy issue in dart-lang/sdk which mentions this one (I think you're right that projects can't span github orgs).

**Comment by jakemac53** [comment]
Note that this package is also used by flutter/flutter and so this may cause issues there too. Although as long as this package stays on an old language version it might still be OK.

**Comment by goderbauer** [comment]
Once this get resolved, we can remove a couple of `ignore`s in the flutter_tool added here: https://github.com/flutter/flutter/pull/123159.

**Comment by bernaferrari** [comment]
I made a PR enabling Dart 3. It was fairly easy. I don't know who is the code owner for this repo, but whoever is, feel free to review when you have time.
