### ISSUE TITLE
_Node is wrong type annotation for validateOverwriteExistingEntity

### ISSUE THREAD

**Issue by srawlins** [google/file.dart#65]
I should not have used `_Node`. I didn't check with the analyzer, but it now says:

```
Analyzing lib...
  error • The argument type '(_DirectoryNode) → Null' can't be assigned to the parameter type '(_Node) → void' at lib/src/backends/memory/memory_directory.dart:76:9 • argument_type_not_assignable
```

**Comment by tvolkert** [comment]
But [here](https://github.com/google/file.dart/blob/99baf3698ac28904b53fe8cb57c8dc8b50589a2b/lib/src/backends/memory/memory_file_system_entity.dart#L238), we call `validateOverwriteExistingEntity(child)`, where `child` is a `_Node`...

Let's back up.  `_RenameOverwriteValidator` is defined [here](https://github.com/google/file.dart/blob/99baf3698ac28904b53fe8cb57c8dc8b50589a2b/lib/src/backends/memory/memory_file_system_entity.dart#L12) like so:

```
typedef void _RenameOverwriteValidator<T extends _Node>(T existingNode);
```

So in [`renameSync`](https://github.com/google/file.dart/blob/99baf3698ac28904b53fe8cb57c8dc8b50589a2b/lib/src/backends/memory/memory_file_system_entity.dart#L210), we want the `validateOverwriteExistingEntity` argument to just be an instance of `_RenameOverwriteValidator`, with the type argument being any subclass of `_Node`.  How do we express this?
