### ISSUE TITLE
Dart 2 runtime failures in tests

### ISSUE THREAD

**Issue by keertip** [google/file.dart#84]
Running the tests in dart 2 mode, see failures 

type 'Future<dynamic>' is not a subtype of type 'Future<String>' where
    Future is from dart:async
    Future is from dart:async
    String is from dart:core
  
  ../../file/test/recording_test.dart        _RecordingClass.futureProperty
  ../../file/test/recording_test.dart 78:12  main.<fn>.<fn>.<fn>

  type '_ControllerStream<dynamic>' is not a subtype of type 'Stream<String>' where
    _ControllerStream is from dart:async
    Stream is from dart:async
    String is from dart:core
  
  ../../file/test/recording_test.dart        _RecordingClass.streamMethod
  ../..file/test/recording_test.dart 96:36  main.<fn>.<fn>.<fn>

 type 'LocalDirectory' is not a subtype of type 'FutureOr<LocalDirectory>' of ':return_value' where
    LocalDirectory is from package:file/src/backends/local/local_directory.dart
    LocalDirectory<optimized out> is from package:file/src/backends/local/local_directory.dart
    Directory is from dart:io
    FutureOr is from dart:async
    LocalDirectory<optimized out> is from package:file/src/backends/local/local_directory.dart
  
  dart:async                                                              _Completer.completeError
  package:file/src/forwarding/forwarding_file_system_entity.dart          ForwardingFileSystemEntity.delete
  ===== asynchronous gap ===========================
  dart:async                                                              _asyncThenWrapperHelper
  package:file/src/forwarding/forwarding_file_system_entity.dart          ForwardingFileSystemEntity.delete
  ../../file/test/common_tests.dart 732:28  runCommonTests.<fn>.<fn>.<fn>.<fn>

and more

**Comment by keertip** [comment]
@matanlurey

**Comment by srawlins** [comment]
I'll take this one.
