### ISSUE TITLE
Dart 2 runtime checks failure

### ISSUE THREAD

**Issue by tvolkert** [google/file.dart#90]
## Steps to reproduce

Create `foo.dart`, containing the following:

```dart
import 'dart:async';

import 'package:file/file.dart';
import 'package:file/local.dart';

Future<void> main() async {
  FileSystem fs = const LocalFileSystem();
  Directory dir = fs.directory('foo')..createSync();
  await dir.rename('baz');
}
```

Run the file in Dart 2 mode:

```sh
$ dart --preview-dart-2 foo.dart
```

## Expected result

A directory named `foo` should be created, then renamed to `baz` (as happens when you run that code in Dart 1 mode).

## Actual result

```
Unhandled exception:
type 'LocalDirectory' is not a subtype of type 'FutureOr<LocalDirectory>' of 'value'
#0      _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart)
#1      ForwardingFileSystemEntity.rename (package:file/src/forwarding/forwarding_file_system_entity.dart)
<asynchronous suspension>
#2      main (file:///Users/tvolkert/project/file.dart/packages/file/foo.dart:9:13)
<asynchronous suspension>
#3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by tvolkert** [comment]
https://github.com/google/file.dart/pull/89 by @mehmetf is meant as a band-aid for this problem, but it'd be better to just get to the underlying issue.

I'm not sure where that `FutureOr<>` reference is even coming from, since `package:file` doesn't refer to `FutureOr<>` anywhere...

@mraleph thoughts?

**Comment by mraleph** [comment]
@tvolkert looking into it.

**Comment by mraleph** [comment]
Reduced and triaged, upstream bug: https://github.com/dart-lang/sdk/issues/33392

**Comment by mraleph** [comment]
Upstream bug has been fixed, so this should be closed.
