### ISSUE TITLE
Testing package

### ISSUE THREAD

**Issue by droidery** [google/file.dart#93]
Is there a way to use the testing package (https://github.com/google/file.dart/tree/master/packages/file_testing) in our projects which use `file.dart`. I'd like to use the matchers in my own unit testers.

**Comment by tvolkert** [comment]
You should be able to add the following to your pubspec.yaml:

```
dev_dependencies:
  file_testing: >=2.0.0
```

Then import `package:file_testing/file_testing.dart` in your tests.  Please re-open this if that's not working.
