### ISSUE TITLE
[Feature request] Upgrade `test` to version 1.3.0

### ISSUE THREAD

**Issue by cedx** [google/file.dart#97]
* Dart SDK : `2.0.0-dev.69.2 (Mon Jul 23 17:10:56 2018 +0200) on "windows_x64"`
* file_testing : `2.0.0`

I'm using the `file_testing` package with the `test` package. The issue is that `file_testing` depends on `test:  ^0.12.33`, but I'm using the version 1.3.0. So I can't install the dependencies of my project :

```
$ pub get
Resolving dependencies...
Because no versions of file_testing match >2.0.0 <3.0.0 and file_testing 2.0.0 depends on test ^0.12.33, file_testing ^2.0.0 requires test ^0.12.33.
So, because my_project depends on both test ^1.3.0 and file_testing ^2.0.0, version solving failed.
Process finished with exit code 1
```

It would be cool if the `test` constraint could be upgraded.

**Comment by cedx** [comment]
Thanks @pq

**Comment by pq** [comment]
Still a little ways to go but getting there!
