### ISSUE TITLE
Declare compatibility with Dart 2 stable

### ISSUE THREAD

**Issue by mit-mit** [google/file.dart#98]
The Dart SDK constraint needs to be updated to [declare compatibility with Dart 2 stable](https://www.dartlang.org/dart-2#upper-constraints-on-the-sdk-version):

1. https://github.com/google/file.dart/blob/master/packages/file/pubspec.yaml#L20
1. https://github.com/google/file.dart/blob/master/packages/file_testing/pubspec.yaml#L13

**Comment by mit-mit** [comment]
cc @tvolkert

**Comment by pq** [comment]
This is done but `file` still needs to be made Dart 2 **_compatible_**.  See #103.
